### ISSUE TITLE
Invalid ServiceFabricException error code for service does not exist

### ISSUE THREAD

**Issue by jijohn14** [Microsoft/service-fabric-client-dotnet#16]
I get error code as UNKNOWN in exception while the exception message has correct code and message "FABRIC_E_SERVICE_DOES_NOT_EXIST. Service does not exist."

![image](https://user-images.githubusercontent.com/17716005/41122993-1f8890b2-6a52-11e8-89fb-dba55b29fc3a.png)

**Comment by amanbha** [comment]
Thanks for reporting @jijohn14 , I will take a look at it.
