### ISSUE TITLE
Logic to pick valid endpoint in endpoint list

### ISSUE THREAD

**Issue by jijohn14** [Microsoft/service-fabric-client-dotnet#18]
If cluster endpoints list has an invalid and valid endpoint, the client behavior is indeterministic because of this. Correct approach will be to walk the endpoints and pick the valid one for all calls.

https://github.com/Microsoft/service-fabric-client-dotnet/blob/d2904b847ec23ba80c934fa1f18f4637b91445e2/src/Microsoft.ServiceFabric.Client.Http/ServiceFabricHttpClient.cs#L374

**Comment by amanbha** [comment]
User, needs to provide correct endpoints.

**Comment by jijohn14** [comment]
This is not consistent with FabricClient behavior in Microsoft.ServiceFabric package which picks the correct endpoint for use.
