### ISSUE TITLE
ApplicationPackageDownloadUri should be Uri datatype

### ISSUE THREAD

**Issue by jijohn14** [Microsoft/service-fabric-client-dotnet#19]
https://github.com/Microsoft/service-fabric-client-dotnet/blob/6875b5c8adf6a9fc63fc6a238484108e56d5867c/src/Microsoft.ServiceFabric.Common/ExternalStoreProvisionApplicationTypeDescription.cs#L33

**Comment by amanbha** [comment]
This is generated from swagger specification so will not be changed.
