### ISSUE TITLE
IServiceFabricClient.Services.CreateService throws exception

### ISSUE THREAD

**Issue by jijohn14** [Microsoft/service-fabric-client-dotnet#21]
IServiceFabricClient.Services.CreateService fails with below exception because of bug in IEquatable implementation for FabricName. PR #20 fixes this issue.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ServiceFabric.Common.FabricName.op_Inequality(FabricName name1, FabricName name2)

**Comment by amanbha** [comment]
Merged PR#20
