### ISSUE TITLE
Add multi-target build for net462 binaries

### ISSUE THREAD

**Issue by jijohn14** [Microsoft/service-fabric-client-dotnet#24]

**Comment by amanbha** [comment]
@jijohn14  Could you please explain it a bit more? This is built for netstandard2.0, so any full .net framework >-= 4.6.1 should run with it.

**Comment by jijohn14** [comment]
@amanbha There are lot of issues with bindings and reference with netstandard 2.0 with our .net 6.2 solutions. I was able to make it work with .net 6.2 target framework. Will share PR.

**Comment by amanbha** [comment]
@jijohn, could you please explain the issues, creating a new project in VS should just work using the shipped nuget package for .net full framework >=4.6.1

**Comment by amanbha** [comment]
Closing it due to inactivity, please feel free to reopen if you have any more questions.

**Comment by jijohn14** [comment]
@amanbha This is being used in a .net 4.6.2 solution which has 120+ projects. When adding the service fabric .net standard library, it adds .net standard 2.0 and several other references (like system.http.net) which breaks the existing bindings. Even after upgrading to later versions of some references, our applications stopped working because missing versions or incompatible dll references.

The only solution was to create a .net 4.6.2 dll version of this dll

**Comment by amanbha** [comment]
@jijohn14 Why adding System.Net.Http will break your existing bindings? That sounds more like an issue with System.Net.Http. The whole promise of netstandard 2.0 library is that it can used both with dotnet framework >4.6.1 and dotnet core > 2.0. If you see it not working and this promise broken, could you open an issue in dotnet standard 2.0 at https://github.com/dotnet/standard

**Comment by jijohn14** [comment]
These issues are already mentioned

**Comment by jijohn14** [comment]
These issues are already mentioned in the project. The promise is not very kept cleanly. I spent a lot of time updating references and fixing different errors for this.
https://github.com/dotnet/standard/issues/481
