### ISSUE TITLE
GetServiceTypeInfoByName fails to parse response

### ISSUE THREAD

**Issue by val-janeiko** [Microsoft/service-fabric-client-dotnet#27]
The following code returns `null`
```csharp
var client = ServiceFabricClientFactory.Create(clusterUri, settings);
return await client.ServiceTypes.GetServiceTypeInfoByNameAsync("MyApplication", "1.0.0.0", "MyServiceType");
```

`ServiceTypeDescriptionConverter.GetFromJsonProperties` throws JsonReader exception with the following message: 
> 'Incorrect discriminator property name IsStateful, Expected discriminator property name is Kind.'

The JSON returned in the response is the following:
```json
{
  "ServiceTypeDescription": {
    "IsStateful": true,
    "ServiceTypeName": "MyServiceType",
    "PlacementConstraints": "",
    "HasPersistedState": true,
    "Kind": "Stateful",
    "Extensions": [],
    "LoadMetrics": [],
    "ServicePlacementPolicies": []
  },
  "ServiceManifestVersion": "1.0.0.0",
  "ServiceManifestName": "MyServiceTypePkg",
  "IsServiceGroup": false
}
```

**Comment by amanbha** [comment]
@val-janeiko This is a known issue with Service Fabric REST gateway, the fix will be available in the next versions of the Service Fabric runtime release.
