### ISSUE TITLE
Intermittent security exception when uploading application packages to SF cluster

### ISSUE THREAD

**Issue by sachinkumarc** [Microsoft/service-fabric-client-dotnet#38]
**Describe the bug**
When using the ImageStore API (ImageStore.UploadApplicationPackageAsync) to upload application packages to SF cluster, the following exception happens intermittently after few files have been uploaded.

InnerException	{System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Http.WinHttpException: A security error occurred
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()}	System.Exception {System.IO.IOException}

**To Reproduce**
Create a ServiceFabricHttpClient instance and use the following API to upload the application package to the SF cluster.

ImageStore.UploadApplicationPackageAsync

After a few files are uploaded to the cluster, the security exception shown above is thrown.

**Expected behavior**
No exception should be thrown during the upload action

**Additional context**

**Comment by amanbha** [comment]
@sachinkumarc This is not repro, were you rolling cluster certs at the time. As we discussed offline, you were planning to add a fix for it, please let me know if that's still the plan.

**Comment by amanbha** [comment]
@sachinkumarc, I am closing this due to lack of response, please feel free to reopen if it's still an issue.
