### ISSUE TITLE
Move UploadApplicationPackageAsync to IApplicationTypeClient

### ISSUE THREAD

**Issue by aL3891** [Microsoft/service-fabric-client-dotnet#4]
Is there a particular reason UploadApplicationPackageAsync IApplicationTypeClient is in IApplicationClient and not IApplicationTypeClient? It feels more related to application types than application instances, but perhaps that's just my gut feeling

**Comment by amanbha** [comment]
@aL3891  UploadApplicationPackage ties more logically with Applications. An Applications' package is uploaded and not ApplciationType's package.

**Comment by aL3891** [comment]
I'd argue that you are in fact uploading an application type version, not an application. After it's uploaded you need to provision it and then create an actual application, using this method does not result in an application being created or manipulated in any way.

It's a matter of taste i suppose, but it seems more consistent to have it on the ApplicationType or even ImageStore interface, rather then the Application

**Comment by amanbha** [comment]
@aL3891 ImageStore makes sense for this as its uploading to image store.

**Comment by amanbha** [comment]
PR#12 addressed this, method moved to IImageStoreClient
