### ISSUE TITLE
Add compression parameter to UploadApplicationPackageAsync 

### ISSUE THREAD

**Issue by aL3891** [Microsoft/service-fabric-client-dotnet#5]
According to the docs UploadApplicationPackageAsync will always compress the package as part of the upload, however, looking at the code it doesn seem like compression is actually performed as this method never seems to be called: 

https://github.com/Microsoft/service-fabric-client-dotnet/blob/71655e0f90c0547f09876975d457957000f25155/src/Microsoft.ServiceFabric.Client.Http/ApplicationClient_.cs#L293 

In any case, there should probably be a parameter for enabling compression or not.

**Comment by amanbha** [comment]
@aL3891 You are correct, the documentation is incorrect, it currently only compresses larger files, will add compressing the whole package as new feature.

**Comment by aL3891** [comment]
Are you taking contributions? i might take a look, should be a fairly small change

**Comment by amanbha** [comment]
Yes @aL3891 , contributions are welcome.

**Comment by amanbha** [comment]
PR merged
