### ISSUE TITLE
Get ReplicaId from ReplicaInfo

### ISSUE THREAD

**Issue by DanYaari** [Microsoft/service-fabric-client-dotnet#55]
Hi,

I am trying to go over all replicas in a specific partition and remove them.
However, to remove the replicas, I need the replicaId. This information is not available in ReplicaInfo which is the result of GetReplicaInfoListAsync (As far as I have seen, the ReplicaId is given in the result of the REST API, but it is not serialized into the ReplicaInfo.
Currently, if removing all replicas from a list is needed, it is needed to parse the Address property from ReplicaInfo to get the ReplicaId.
I think the ReplicaId should be added to the ReplicaInfo class to provide easy access (as several methods require the ReplicaId parameter). This behavior will be more inline with QueryManager.GetReplicaListAsync in the Service Fabric SDK, as each Replica contains the ID there.

Here is an example of working code with the Service Fabric SDK:
```
await (await fabricClient.QueryManager.GetReplicaListAsync(partitionid)).
                                            ForEachAsync(
                                                async replica => await fabricClient.ServiceManager.RemoveReplicaAsync(
                                                    replica.NodeName,
                                                    partitionid,
                                                    replica.Id,
                                                    true))
```

When trying to replicate the code using Microsoft.ServiceFabric.Client.Http:
```
await (await serviceFabricClient.
                                            Replicas.
                                            GetReplicaInfoListAsync(
                                                partitionId,
                                                cancellationToken: _cancellationToken)).
                                            Data.
                                            ForEachAsync(
                                                async replica => await serviceFabricClient.
                                                    Replicas.
                                                    RemoveReplicaAsync(
                                                    replica.NodeName,
                                                    partitionId,
                                                    /* No access to replica.Id, need to parse replica.Address */,
                                                    true))
```

Thanks for the help,
Dan Yaari

**Comment by amanbha** [comment]
@DanYaari  You can cast ReplicaInfo to StatefulServiceReplicaInfo (for stateful) and access ReplicaId property OR to StatelessServiceInstanceInfo for stateless and access InstanceId property.

**Comment by DanYaari** [comment]
@amanbha Thanks for the quick response.
I will do just that (started with doing it with reflection to get the non public ReplicaId property).
Is there a reason to keep the ReplicaId propery non-public though, as it is used by all of the derived classes and public there.

Thanks,
Dan

**Comment by amanbha** [comment]
@DanYaari ReplicaId property is public on the derived class, its not exposed on ReplicaInfo class., https://github.com/Microsoft/service-fabric-client-dotnet/blob/develop/src/Microsoft.ServiceFabric.Common/Generated/StatefulServiceReplicaInfo.cs#L66

Please correct me, if I am missing something here.

**Comment by amanbha** [comment]
I am closing this as the question has been answered, please feel free to reopen fi you have any more questions.
