### ISSUE TITLE
Incorrect string in SafetyCheckConverter

### ISSUE THREAD

**Issue by DanYaari** [Microsoft/service-fabric-client-dotnet#57]
Hi,
With the latest version of service fabric (6.4.622.9590), I have seen that we have property value of "WaitForInBuildReplica" instead of "WaitForInbuildReplica" as appears in SafetyCheckConverter.
As the string comparison is case sensitive, I receive "Unknown Kind." thrown.
I have reproduced this with a local service fabric cluster.

Thanks,
Dan

**Comment by caminadab** [comment]
Thanks for reporting. I'll get it fixed.

**Comment by amanbha** [comment]
We will update the swagger specification to use correct value "WaitForInBuildReplica". Once swagger is updated, new generated client library will have the fix.

**Comment by amanbha** [comment]
This has been fixed and fix is available in nuget package >=2.0.0-preview13
