### ISSUE TITLE
ImageStore operations for dev clusters (FileSystem)

### ISSUE THREAD

**Issue by PepijnGramberg** [Microsoft/service-fabric-client-dotnet#6]
All operations on the ImageStore give exceptions when using the client with a dev cluster. (also UploadApplicationPackageAsync)
`Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: FABRIC_E_SERVICE_DOES_NOT_EXIST. Service does not exist.`

The reason is the lack of an ImageStoreService in a dev cluster. It uses the file system instead. The old fabric client api could handle this as you specified the ImageStoreConnectionString (filepath incase of a dev cluster). 

Will there come support for the file system imagestore in this client aswell?

**Comment by amanbha** [comment]
Yes @PepijnGramberg, the support for file system based image store will be added. I will assign this to myself, feel free to raise a PR if you get  to it before me :). Inthis first preview release support for apis exposed through Service Fabric REST apis is added.

**Comment by aL3891** [comment]
I anticipate i'll be able to look at this either today or beginning next week (we need it as well) 
Have you started any work on this yet?

**Comment by amanbha** [comment]
Thanks @aL3891. I haven't started it yet, you can start on it. We can move these Upload methods to IImageStoreClient as we were discussing in #4

**Comment by aL3891** [comment]
@PepijnGramberg I've made a reasinably finished PR for this now, feel free to take a look and see that your scenarios are covered

**Comment by PepijnGramberg** [comment]
@aL3891 looks good on first glance, currently not able to test it. Maybe next week
