### ISSUE TITLE
New-SFReplicaHealth always error out with "A required parameter is missing: ServiceKind"

### ISSUE THREAD

**Issue by erhuan-msft** [Microsoft/service-fabric-client-dotnet#63]
**Description**

New-SFReplicaHealth and the equivalent C# client method ReportReplicaHealthAsync always exception out with message "A required parameter is missing: ServiceKind".

**To Reproduce**

````powershell
New-SFReplicaHealth -PartitionId dc39bb20-fc29-4008-89bd-2d89dcfae2e3 -ReplicaId 131957984827086818 -ReplicaHealthReportServiceKind Stateless -SourceId Test -Property Hello -HealthState Warning
New-SFReplicaHealth : A required parameter is missing: ServiceKind.
At line:1 char:1
+ New-SFReplicaHealth -PartitionId dc39bb20-fc29-4008-89bd-2d89dcfae2e3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-SFReplicaHealth], ServiceFabricException
+ FullyQualifiedErrorId : NewReplicaHealthErrorId,Microsoft.ServiceFabric.Powershell.Http.NewReplicaHealthCmdlet
````

**Expected behavior**

We expect this command to work and set the health state to Warning for that replica.

**Additional context**

I looked up on Service Fabric code and the REST API was actually expecting ServiceKind in query param instead of ReplicaHealthReportServiceKind so this seems like a bug on client library. My cluster version is 6.4.622.9590

**Comment by amanbha** [comment]
@erhuan-msft Does a direct rest call to the container succeeds, i see that as per REST spec for this api,  it expects ReplicaHealthReportServiceKind so it could be a runtime issue.
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-reportreplicahealth

**Comment by erhuan-msft** [comment]
The RESTful API doc seems to be incorrect as well. Here are my tests and only the last one works (Used ServiceKind=1 in query parameter).

```
POST http://localhost:19080/Partitions/278d2ab0-e45c-4498-9ee5-6017404661c5/$/GetReplicas/131956793066922345/$/ReportHealth?api-version=6.0&ReplicaHealthReportServiceKind=Stateless&Immediate=false&timeout=5 HTTP/1.1
Host: localhost:19080
Content-Length: 71
Content-Type: application/json

HTTP/1.1 400 Bad Request
Content-Length: 91
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
X-Content-Type-Options: nosniff
Date: Thu, 28 Feb 2019 22:40:34 GMT

{"Error":{"Code":"E_INVALIDARG","Message":"A required parameter is missing: ServiceKind."}}
```

```
POST http://localhost:19080/Partitions/278d2ab0-e45c-4498-9ee5-6017404661c5/$/GetReplicas/131956793066922345/$/ReportHealth?api-version=6.0&ServiceKind=Stateless&Immediate=false&timeout=5 HTTP/1.1
Host: localhost:19080
Content-Length: 71
Content-Type: application/json

HTTP/1.1 400 Bad Request
Content-Length: 78
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
X-Content-Type-Options: nosniff
Date: Thu, 28 Feb 2019 22:40:48 GMT

{"Error":{"Code":"E_INVALIDARG","Message":"Invalid service kind: Stateless."}}
```

```
POST http://localhost:19080/Partitions/278d2ab0-e45c-4498-9ee5-6017404661c5/$/GetReplicas/131956793066922345/$/ReportHealth?api-version=6.0&ServiceKind=1&Immediate=false&timeout=5 HTTP/1.1
Host: localhost:19080
Content-Length: 71
Content-Type: application/json

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
X-Content-Type-Options: nosniff
Date: Thu, 28 Feb 2019 22:44:41 GMT
Content-Length: 0

```

**Comment by amanbha** [comment]
@erhuan-msft  Thanks for the update, yes, the swagger spec and api implementation are different, we will update it for next release.

**Comment by erhuan-msft** [comment]
Is this fixed in the just release update or will be in 6.5? https://blogs.msdn.microsoft.com/azureservicefabric/2019/03/12/azure-service-fabric-6-4-refresh-release-2/

**Comment by amanbha** [comment]
@erhuan-msft it will be fixed in 6.5, sorry I should have been more clear in my previous response, by next release I meant next version release and not a refresh.

**Comment by TheReaLee** [comment]
What is the status of this? As I also have encountered this issue.

**Comment by danielwgrech** [comment]
Also waiting on this.  Any update?

**Comment by amanbha** [comment]
@TheReaLee  @danielwgrech  The runtime and swagger spec is fixed in 6.5 release. I will release the new client library with fixes soon.

**Comment by amanbha** [comment]
The package with fix is now published https://www.nuget.org/packages/Microsoft.ServiceFabric.Client.Http/3.0.0-preview16

**Comment by atifield** [comment]
Is 2.0.0-preview13 backward compatible with 6.4 cluster?

**Comment by amanbha** [comment]
Yes, 2.0.0-preview* is for use with cluster >=6.4
3.0.0.0-preview* is for use with cluster >=6.5

**Comment by atifield** [comment]
Thanks for clarification. I meant to ask about 3.0.0-preview16. By the way, earlier version is not compatible with 6.5. Had issue with 2.0.0-preview1 on 6.5 cluster.

**Comment by amanbha** [comment]
@atifield what's the issue you are seeing with using 2.0.0-preview1 with 6.5 cluster. Could you please try 2.0.0.0:preview12 as it has some bug fixes over 2.0.0-preview1

**Comment by atifield** [comment]
I have partial stacktrace here. I didn't pinpoint the exact call that failed but judging from failed to parse `PropertyName`. I am guessing it was either GetApplicationInfoList or GetServiceInfoList that failed on 6.5 cluster. Upgrading to 2.0.0-preview13 made the issue go away.

```
Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: Failed to deserialize json response from server. ---> Newtonsoft.Json.JsonReaderException: Unexpected JsonToken PropertyName.
 at void Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadStartObject(JsonReader reader)
 at T Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.Deserialize<T>(JsonReader reader, Func<JsonReader, T> getFromJsonPropertiesFunc)
 at List<T> Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadList<T>(JsonReader reader, Func<JsonReader, T> deserializerFunc)
 at PagedData<T> Microsoft.ServiceFabric.Client.Http.Serialization.PagedDataConverter<T>.GetFromJsonProperties(JsonReader reader, Func<JsonReader, T> deserializeFunc)
 at PagedData<T> Microsoft.ServiceFabric.Client.Http.Serialization.PagedDataConverter<T>.Deserialize(JsonReader reader, Func<JsonReader, T> deserializeFunc)
 at async Task<PagedData<T>> Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncGetRespon
```

**Comment by amanbha** [comment]
@atified, yes the issue was fixed in the update nuget pkg release.
