### ISSUE TITLE
JsonReaderException raised from InfrastructureClient

### ISSUE THREAD

**Issue by dvoskuil** [Microsoft/service-fabric-client-dotnet#65]
**Describe the bug**
The following two InfrastructureClient APIs always fail with a Newtonsoft.Json.JsonReaderException when valid commands are passed in.
```
InfrastructureClient.InvokeInfrastructureQueryAsync()
InfrastructureClient.InvokeInfrastructureCommandAsync()

Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: Failed to deserialize json response from server. ---> Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: None.
   at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadValueAsString(JsonReader reader)
   at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.<SendAsyncGetResponse>d__26`1.MoveNext()
```

**To Reproduce**
```
IServiceFabricClient client = ...
var infraServices = await client.Services.GetServiceInfoListAsync("System", "InfrastructureServiceType");
foreach (var svc in infraServices.Data)
{
    string result1 = await client.Infrastructure.InvokeInfrastructureQueryAsync(queryCommand, svc.Id);
    string result2 = await client.Infrastructure.InvokeInfrastructureCommandAsync(adminCommand, svc.Id);
}
```

**Expected behavior**
These commands are expected to work when valid commands are passed in.

**Additional context**

The InvokeInfrastructureCommandAsync and InvokeInfrastructureQueryAsync APIs only return strings, presumably to support returning different kinds of JSON results for the different commands that can be passed in. So the APIs should just pass thru the raw JSON response content string to the caller, instead of trying to do any kind of special parsing or deserialization like what is happening in JsonReaderExtensions.ReadValueAsString(JsonReader).

**Comment by amanbha** [comment]
Fixed in 2.0.0-preview11 version of nuget package
