### ISSUE TITLE
Update IServiceFabricClient to implement IDisposable

### ISSUE THREAD

**Issue by GePerez** [Microsoft/service-fabric-client-dotnet#74]
I'm creating this issue per the guidelines on [Contributing.md](https://github.com/Microsoft/service-fabric/blob/master/CONTRIBUTING.md).

As agreed over email, I will update IServiceFabricClient to implement IDisposable so that when the IServiceFabricClient object gets collected it does not leak the internal IDisposable objects like HttpClient.

**Comment by amanbha** [comment]
Fixed https://github.com/microsoft/service-fabric-client-dotnet/pull/75
