### ISSUE TITLE
Copy-SFApplicationPackage returns "The operation was canceled." with no indication why or docs explaining the issue

### ISSUE THREAD

**Issue by K-Cully** [Microsoft/service-fabric-client-dotnet#76]
**Describe the bug**
When calling Copy-SFApplicationPackage, the majority of the time, a message "The operation was canceled." is returned, with no other information.
Of 8 attempts calls, I've seen one succeed, so the command is correct.

**To Reproduce**
Generate a pkg folder 205 MB in size.
Connect to a secure SF Cluster using cert thumbprint identification with Connect-SFCluster 
Run command:
`Copy-SFApplicationPackage -ApplicationPackagePath "PathToPkgFolder" -ApplicationPackagePathInImageStore "AppType"`

**Expected behavior**
The command is successful the majority of the time and a useful error is returned when it fails.

**Comment by amanbha** [comment]
This should be fixed PS Module Release 1.4.1-preview1 version has the fix., if it still repros, please feel free to reopen
