### ISSUE TITLE
Services.UpdateServiceAsync can't change instance count.

### ISSUE THREAD

**Issue by JackyChiou** [Microsoft/service-fabric-client-dotnet#80]
**Describe the bug**

await client.Services.UpdateServiceAsync("ServiceFabricApp1~Stateless1", new StatelessServiceUpdateDescription(instanceCount: 5, defaultMoveCost: Microsoft.ServiceFabric.Common.MoveCost.Zero));

after the API returned succeed but nothing changed for the service in cluster explorer.

Do the same operation in PowerShell, the InstanceCount would be changed.
Update-ServiceFabricService -Stateless fabric:/ServiceFabricApp1/Stateless1 -InstanceCount 5 

**To Reproduce**
Steps or code snippet to reproduce the behavior.
Func<CancellationToken, Task<SecuritySettings>> GetSecurityCredentials = (ct) =>
            {
                // get the X509Certificate2 either from Certificate store or from file.
                var clientCert = new System.Security.Cryptography.X509Certificates.X509Certificate2(@"C:\Users\jchiou\jackysf320191031213903.pfx", "Password01!");
                var remoteSecuritySettings = new RemoteX509SecuritySettings(new List<string> { "8AB797576F2EF93574631A6BD7C5B381C86A60C4" });
                return Task.FromResult<SecuritySettings>(new X509SecuritySettings(clientCert, remoteSecuritySettings));
            };

            // create client using ServiceFabricClientBuilder.UseX509Security
            var client = new ServiceFabricClientBuilder()
                            .UseEndpoints(new Uri(@"https://jackysf3.eastasia.cloudapp.azure.com:19080"))
                            .UseX509Security(GetSecurityCredentials)
                            .BuildAsync().GetAwaiter().GetResult();

// you can change serviceId and instanceCount
await client.Services.UpdateServiceAsync("ServiceFabricApp1~Stateless1", new StatelessServiceUpdateDescription(instanceCount: 5, defaultMoveCost: Microsoft.ServiceFabric.Common.MoveCost.Zero));

            var serviceDesc = await client.Services.GetServiceDescriptionAsync("ServiceFabricApp1~Stateless1");

**Expected behavior**
Instance Count is changed as we assigned.

**Additional context**

**Comment by amanbha** [comment]
This is a known issue when flags are not provided.

Could you please provide a valid value for flag:

Flags is an integer indicating which properties actually need to be updated, each bit corresponds to one property.

For example, if you want to update DefaultMoveCost, you should set the flags to value 512.

For more info about Flags, you can check this link: https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-statefulserviceupdatedescription#flags

**Comment by JackyChiou** [comment]
Thank you for your help. I verified that in my environment. Thank you. Jacky

從我的iPhone傳送

Aman Bhardwaj <notifications@github.com> 於 2019年11月1日 下午12:51 寫道：

﻿

This is a known issue when flags are not provided.

Could you please provide a valid value for flag:

Flags is an integer indicating which properties actually need to be updated, each bit corresponds to one property.

For example, if you want to update DefaultMoveCost, you should set the flags to value 512.

For more info about Flags, you can check this link: https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-statefulserviceupdatedescription#flags<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Frest%2Fapi%2Fservicefabric%2Fsfclient-model-statefulserviceupdatedescription%23flags&data=02%7C01%7C%7C46942a557e5e44c061d408d75e872537%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637081806851792215&sdata=a4U22yV3vuFFqoX5eOSQEebc7TD3RyIUXZ%2BrSxm7ep4%3D&reserved=0>

**Comment by JackyChiou** [comment]
Resolved.
