### ISSUE TITLE
How are PowerShell help files generated for this repository?

### ISSUE THREAD

**Issue by andrewtyped** [Microsoft/service-fabric-client-dotnet#85]
I see that Microsoft.ServiceFabric.Powershell.Http-Help.xml is stored in the repository, and the build depends on this file's presence. Are you able to share how this file is generated? As far as I can tell, the build isn't responsible for it, and no generation tools are referenced by the repository.

Thank you for making this module available!

**Comment by amanbha** [comment]
@andrewtyped The rest api and powershell is generated usign a tool leveraging AutoRest from the swagger rest api specification for service fabric.

**Comment by andrewtyped** [comment]
Thank you. Is this the tool you're referring to: https://github.com/Azure/autorest.powershell ? If so, would you accept a PR updating the docs to refer to this dependency?

**Comment by amanbha** [comment]
No thats not we use exactly, the tool does use Autorest to generate the models from swagger, but then it generates customized code based on extensions specified in the swagger files, the entire client library in this repo has customized serialization/deserialization logic.
