### ISSUE TITLE
"A task was canceled." error executing Copy-SFApplicationPackage

### ISSUE THREAD

**Issue by shmartel** [Microsoft/service-fabric-client-dotnet#87]
**Is your feature request related to a problem? Please describe.**
Yes.  When using Copy-SFApplicationPackage to copy a larger package, the cmdlet times out and cancels the copy.  The result is only a partial copy of the package to the Image Store.  So, the application can't be used. Example/repro:

> Copy-SFApplicationPackage -ApplicationPackagePath <local-path-of-package> -ApplicationPackagePathInImageStore <image-store-path>
A task was canceled.

We are seeing this error for our package that is ~ 51MB.  It's possible the issue occurs for smaller packages. Note that no stack error is returned, just the "A task was canceled." message.  It seems the default time in this cmdlet is too small.

**Describe the solution you'd like**
Add a timeout parameter is added to Copy-SFApplicationPackage.  Thus, we can increase the timeout to try to avoid this issue.  

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by amanbha** [comment]
Fixed with PR #89 PS Module Release 1.4.1-preview1 version has the fix.
